# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:       /:categories/:title

# Setup
title:            Words
tagline:          'None'
description:      'An effort to commit a state, before it becomes another.'
baseurl:          /

author:
  name:           'Vignesh'

paginate:         3

collections:
  category:
    output: true

defaults:
-
  scope:
    path: ""
    type: category
  values:
    layout: "category"