# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:       /posts/:title

# Setup
title:            Pieces
tagline:          'None'
description:      'An effort to commit a state, before it becomes another.'
baseurl:          /writings
url:              https://jaivigneshvenugopal.github.io"

author:
  name:           'Vignesh'

collections:
  category:
    output: true

defaults:
-
  scope:
    path: ""
    type: category
  values:
    layout: "category"