# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Words
tagline:          'None'
description:      'An effort to commit a state, before it becomes another.'
baseurl:          /

author:
  name:           'Vignesh'

paginate:         10
